apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - replaced-by-kustomize.invalid
      tls:
        mode: SIMPLE
        credentialName: kubeflow-tls
